spring:
  application:
    name: uopp-email-sender
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  mail: # for local env, on prod - specify configs for real mail server
    host: localhost
    username: phello
    password: uhello
    port: '4025'

application:
  rabbitmq:
    queue: email.queue
  uopp-spa:
    moderatorLink: http://localhost:8081/moderator/sign-in
  email:
    encoding: utf-8
    opportunity-notification:
      from: uopp@education.com
      subject: Opportunity notification
